--- 
artifacts: 
  files: 
    - "**/*"
phases: 
  build: 
    commands: 
      - "echo \"This is build phase... \""
  post_build: 
    commands: 
      - "echo \"Deploying to the Lambda\""
version: 0.2
